name: herome
description: "Une application pour chercher et découvrir des superhéros."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true

# Configuration for flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
